spring:
  application:
    name: discovery-center
server:
  port: 2222

eureka:
  instance:
    #hostname: eureka1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  server:
    enable-self-preservation: false  #关闭自我保护
