eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka2:2222/eureka/,http://eureka1:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

management:
  security:
    enabled: false

server:
  port: 7777

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          username: mweidlut
          password: 'yourPWD'
          searchPaths: /config-repo
          uri: https://github.com/mweidlut/SpringCloudDemoConfigCenter.git
    bus:
      enabled: true
  profiles:
    active: test
  rabbitmq:
    addresses: 10.139.60.131:5672
    username: kkuser
    password: kkuser123
    virtual-host: /