spring:
  application:
    name: eureka-client
server:
  port: 3002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/,http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2  #instance到server的刷新周期
    lease-expiration-duration-in-seconds: 5   #server等待的超时时间